### ISSUE TITLE
Fails silently for me. 

### ISSUE THREAD

**Issue by joereddington** [ferrine/md-img-paste.vim#12]
Plugin installs, mapping is active, but plugin fails silently either with mapping or by calling 

:call mdip#MarkdownClipboardImage()

directly. Any ideas? 

PS - The 'img' directory is created... but is also empty...

**Comment by joereddington** [comment]
![Screenshot 2019-05-27 at 11 37 13](https://user-images.githubusercontent.com/4369547/58414633-e1d5f280-8073-11e9-8fec-410685fe4c88.png)

Some debugging reveals that the problem is that it thinks my vim is running on a unix system rather than macos: removing the if statement causes the plugin to work correctly. :/

**Comment by ferrine** [comment]
Hi, Could you please submit a pr with a bugfix? I think you need to figure
out what is your check for macos

**Comment by joereddington** [comment]
Done :)

**Comment by Hritik14** [comment]
@joereddington  Please close this issue if it has been solved.
