### ISSUE TITLE
Allow inputting image name

### ISSUE THREAD

**Issue by lucasdf** [ferrine/md-img-paste.vim#15]
I made a change to be able to input the name of the image instead of using the current date, as it is now.

Would you be interested in including this to the plugin?

**Comment by ferrine** [comment]
Hi, it looks like a nice feature. Would be great if you open a pull request. I will be able to run the code on my arch machine only. So the only question is whether it works on macos/windows

**Comment by Sirius-A** [comment]
I was just looking for this as well. @lucasdf An MR would be highly appreciated :heart:

**Comment by lucasdf** [comment]
Closed by https://github.com/ferrine/md-img-paste.vim/pull/16
