### ISSUE TITLE
hangs on mac if file is in directory with space

### ISSUE THREAD

**Issue by JakeWrights** [ferrine/md-img-paste.vim#19]
Hi, the plugin doesn't seem to work when the folder of your file has spaces in it. I tried different directories with and without spaces and this seems to be the case. It simply hangs after asking for file name

I tried scanning the code but couldn't find the error

Thanks!

**Comment by ferrine** [comment]
I think the error might come from non escaped names.
https://github.com/ferrine/md-img-paste.vim/blob/e29daecf5c068c1862242bb006084e2bcde54f07/plugin/mdip.vim#L47
```
    let tmpfile = a:imgdir . '/' . a:tmpname . '.png'
```
I'm not sure though, but it's definitely worth fixing. PR is more than welcome as I have little time to debug till March

**Comment by ferrine** [comment]
Can you please try to escape directory or file name in the script? Hope it is the case

**Comment by eternityz** [comment]
I think I have a fix #28.  `outdir` should not be escaped in `s:SafeMakeDir` on mac.
