### ISSUE TITLE
Does not work in MacVim

### ISSUE THREAD

**Issue by stvhwrd** [ferrine/md-img-paste.vim#2]
I'm using a `.vimrc` configuration that is verified working in vim within [iTerm2](https://iterm2.com/) (terminal emulator).  The plugin works really well in the terminal instance of vim.

In [MacVim](https://github.com/macvim-dev/macvim), the plugin does not work properly.  It inserts an image link in the markdown file, but doesn't increment the image name.

* Every image link in the Markdown appears as `![](img/image0.png)`  - it is not incremented from `0`.
* The images are correctly moved from the system clipboard into the `img` folder, but each one is named `tmp.png` (never renamed `image0`, `image1`, etc.) so each successive image overwrites the file.

May be interesting to test with gVim on Linux.

**Comment by stvhwrd** [comment]
Following up, the plugin works great in `vim-gtk` on Ubuntu 16.04.3 LTS.  The issue is specifically MacVim, it seems.

**Comment by stvhwrd** [comment]
Same problem is present in [VimR](http://vimr.org/).

**Comment by ferrine** [comment]
sounds strange. Currently I lack test environment, seeking for solutions

**Comment by ferrine** [comment]
I got a kind of working test for my environment. There were some problems to emulate user behaviour and his clipboard. Testing such things is crazy. Have you fixed your problem?

**Comment by ferrine** [comment]
I made things work with screenshots. I've tried individual function calls from shell having screenshot in my clipboard

    :call SaveFileTMPMacOS('/Users/ferres/Downloads', 'tmp')
    :call SaveNewFile('/Users/ferres/Downloads', '/Users/ferres/Downloads/tmp.png') 

Copying any image to clipboard with cmd+C does not work, I get weird tmp.png image from the first call

**Comment by ferrine** [comment]
Closing too old issues
