### ISSUE TITLE
problem on macOS 

### ISSUE THREAD

**Issue by darlingof02** [ferrine/md-img-paste.vim#33]
When I ran this plug-in, I came across the error below. And I find the function "SaveFileTMP()", specifically, the function "IsWSL()", has some trouble. Because when I try to run the function "has("unix")", it keeps telling me "TRUE". However, I don't have such a file named "/proc/version".
By the way, my OS version is macOS 10.15.6 and my vim version is 8.2.1400.
My Error (some of them are Chinese, you can translate them)
<img width="677" alt="截屏2020-08-12 下午7 14 02" src="https://user-images.githubusercontent.com/35373874/90009374-7efc6580-dcd0-11ea-87c0-01a37980c539.png">
My Experiment
<img width="648" alt="截屏2020-08-12 下午7 14 36" src="https://user-images.githubusercontent.com/35373874/90009579-e2869300-dcd0-11ea-9afd-f78a3de3ecfc.png">

**Comment by ferrine** [comment]
Can you figure out what actual branch is called here?
![SmartSelect_20200812-145723_Chrome](https://user-images.githubusercontent.com/11705326/90012540-3cc12d00-dcac-11ea-9837-298c11c91718.jpg)

**Comment by ferrine** [comment]
Is it WSL?

**Comment by darlingof02** [comment]
Yes, I change the order of the four " if - else” structure and put the second one “s:os == Darwin”  in the first “if”. It turns out it works temporarily.

**Comment by RicoToothless** [comment]
face the same issue here.

**Comment by ferrine** [comment]
I'm neither MacOS nor WSL user, I'll need help to create a fixing PR that is compatible with all popular distros: Linux, Windows, WSL, MacOS

**Comment by ferrine** [comment]
Same as #38
