### ISSUE TITLE
Every single time I run the command, this shows up

### ISSUE THREAD

**Issue by presmihaylov** [ferrine/md-img-paste.vim#35]
![image](https://user-images.githubusercontent.com/7642330/90973762-b0c1c780-e52d-11ea-8c40-d01d0398a837.png)

I'm running on a macOS Catalina. This is my [entire vimrc configuration](https://github.com/preslavmihaylov/dotfiles).

**Comment by ferrine** [comment]
related to #33

**Comment by ferrine** [comment]
Same as #38
