### ISSUE TITLE
WSL function resets terminal font and raises "No such file or directory"

### ISSUE THREAD

**Issue by hexcowboy** [ferrine/md-img-paste.vim#38]
![ezgif-7-d0516241f619](https://user-images.githubusercontent.com/8162609/92148500-4db01a80-ede2-11ea-9096-9b89fccfb31a.gif)

The  issue of #33 and #35 resulted in an error occurring, and then the `s:SaveFileTMPLinux` function running after the error. That issue affects macOS and WSL systems.

#36 fixed the problem for macOS and Windows. Now instead of throwing and error and running `s:SaveFileTMPLinux`, [`s:SaveFileTMPWSL`](https://github.com/ferrine/md-img-paste.vim/blob/33fc645ca41f7e06130262af2b033a4a91890f88/plugin/mdip.vim#L32) is called and breaks the terminal.

My advice would be to remove the WSL function and let the `s:SaveFileTMPLinux` function run when WSL is detected.

**Comment by ferrine** [comment]
Can you propose this workaround in the recent pr?

**Comment by hexcowboy** [comment]
Font resetting is a product of this issue https://github.com/microsoft/terminal/issues/280

**Comment by jackno** [comment]
@MatchaChoco010 can you explain why
