### ISSUE TITLE
make the default name of the image in the md be what you name the file

### ISSUE THREAD

**Issue by keblek** [ferrine/md-img-paste.vim#39]
When I paste the image the name defaults to `Image` unless I edit it. 

Can it just be whatever I name the file as?

**Comment by keblek** [comment]
I realised that the default behaviour is already much better than what I am suggesting. 

Looking forward to the next patch!

**Comment by lucasdf** [comment]
hey @keblek I have implemented exactly your suggestion here https://github.com/ferrine/md-img-paste.vim/pull/44

You might want to update your version to check it out. What exactly you meant by "the default behavior is already much better"? Do you think having the name as `Image` is better?
