### ISSUE TITLE
Editable File Names Required.

### ISSUE THREAD

**Issue by cf020031308** [ferrine/md-img-paste.vim#4]
Hello, ferrine.

I'm using this plugin and it really suits my work except for one thing that I can only name a specific image file with a random name or a fixed name but not a meaningful name.

So could you please improve it? My suggestion is as followed: 

```git
diff --git a/plugin/mdip.vim b/plugin/mdip.vim
index ee3eff4..ea71c4f 100644
--- a/plugin/mdip.vim
+++ b/plugin/mdip.vim
@@ -74,7 +74,7 @@ endfunction
 function! mdip#MarkdownClipboardImage()
     let workdir = SafeMakeDir()
     " change temp-file-name and image-name
-    let g:mdip_tmpname = RandomName()
+    let g:mdip_tmpname = input("File Name? ", RandomName())
```

Thanks again for your cool plugin.

**Comment by ferrine** [comment]
Hi, I can check it in the evening! Glad to hear you have a PR (open it) :)

**Comment by ferrine** [comment]
At a first glance you change only tmp name but not final one

**Comment by ferrine** [comment]
Got it, looks like newer version of plugin now creates random name... So you are doing right
