### ISSUE TITLE
Extend to other markup languages

### ISSUE THREAD

**Issue by krisgry** [ferrine/md-img-paste.vim#42]
Hi,
Thanks for a great plugin! Exactly what I was looking for when taking notes and writing summaries in my personal wiki.

Would it be possible to extend this to other markup languages as well? I can definitely see the use of having similar behaviour in e.g. LaTeX. I'm no vimscript expert, but one solution could be to change the hard-coded inserts in 
https://github.com/ferrine/md-img-paste.vim/blob/94c23fc5ce9929fc0b5cfb0b4b80b5afe6ac4ebe/plugin/mdip.vim#L179 and https://github.com/ferrine/md-img-paste.vim/blob/94c23fc5ce9929fc0b5cfb0b4b80b5afe6ac4ebe/plugin/mdip.vim#L181 to insert the variables `g:mdip_paste_before` and `g:mdip_paste_after` instead of `![Image](` and `)`, respectively. Then one could define the `g:mdip_paste_` variables based on filetype:
```
autocmd FileType latex let g:mdip_paste_before = '\includegraphics{'
autocmd FileType latex let g:mdip_paste_after = '}\n\caption{Image}'
autocmd FileType markdown let g:mdip_paste_before = '![Image]('
autocmd FileType markdown let g:mdip_paste_after = ')'
```
This would also make it possible to define the variables as empty, such that only the image path is pasted.

There are probably better ways to do this, to make it more aligned with ftplugin and snippets, but that is beyond my knowledge.

**Comment by ferrine** [comment]
That sounds really cool. I like the proposal

**Comment by ferrine** [comment]
I'm neither a vim expert:) I learned vim scripting deciding to do this project. I'll definitely need more people involved here to maintain the extension for life-happens reasons. As for now, I'll tag this as "help wanted" and keep open.

You are welcome to open a PR and we'll see where it goes. This repo exists thanks to collaborative efforts of vim geeks that come here and use the package, fix bugs, etc. I'm very open to new ideas and people!

**Comment by krisgry** [comment]
Thanks for the encouragement :) I had a closer look at this. My suggested approach unfortunately breaks the functionality where the "Image" text is selected, such that the user can easily change it.

One option could be to have three strings(`let g:mdip_paste_prefix = '![I'`, `let g:mdip_paste_before = 'mage]('` and `let g:mdip_paste_after = ')'`), and change 
https://github.com/ferrine/md-img-paste.vim/blob/94c23fc5ce9929fc0b5cfb0b4b80b5afe6ac4ebe/plugin/mdip.vim#L179-L183
to
```        
        execute "normal! i" . g:mdip_paste_prefix
        let ipos = getcurpos()
        execute "normal! a" . g:mdip_paste_before . relpath . g:mdip_paste_after
        call setpos('.', ipos)
        execute "normal! ve\<C-g>"
```
But I do not really like this solution, as it is not very flexible. For example, for pasting a latex image you would want the path to come before the selected "Image"-text:
```
\includegraphics[width=0.5\textwidth]{path/to/image.jpg}
\caption{Image}
```
(as placing the `\caption` before the `\includegraphics' places the caption above the image)

A more flexible solution would be to replace the above snippet with 
```
call call(g:PasteImageFunction, [relpath])
```
This would allow the user to define the function for pasting the image themselves, possibly on a filetype basis:
```
function! g:MarkdownPasteImage(relpath)
        execute "normal! i![I"        
        let ipos = getcurpos()
        execute "normal! a" . "mage](" . relpath . ")"
        call setpos('.', ipos)
        execute "normal! ve\<C-g>"
endfunction

function! g:LatexPasteImage(relpath)
       execute "normal! i\\includegraphics{" . a:relpath . "}\r\\caption{I"  
        let ipos = getcurpos()
        execute "normal! a" . "mage}" 
        call setpos('.', ipos)
        execute "normal! ve\<C-g>"
endfunction

function! g:PasteImagePath(relpath)
      execute "normal! i" . a:relpath 
endfunction

autocmd FileType markdown let g:PasteImageFunction = 'g:MarkdownPasteImage'
autocmd FileType tex let g:PasteImageFunction = 'g:LatexPasteImage'
```

I also tried `let g:PasteImageFunction = 'g:PasteImagePath'` (without an autocmd), as I feel that would make the most sense for the general case (which I realise could be controversial for a plugin named 'md-img-paste.vim' :)), but I could not get it to work along with the lets using autocmd above. Any suggestions on how that can be achieved?

**Comment by ferrine** [comment]
I personally do not value much this cursor feature

**Comment by ferrine** [comment]
The approach with custom functions makes sense but requires to be documented

**Comment by rwmitchell** [comment]
I came for the same thing.  I use hyperlist for my notes and it expects links to be inside <> instead of ().
After I changed the bracketing, 'gf' opened the file in Preview just like I wanted.  I'm sure I could edit the plugin, but it would break on the next update.
