### ISSUE TITLE
Under Linux support Wayland

### ISSUE THREAD

**Issue by the42** [ferrine/md-img-paste.vim#46]
Walyand is the new display server for Linux. It does not use xsel. The clipboard tool for Wayland is wl-clipboard:

https://github.com/bugaevc/wl-clipboard

As a starter, NeoVim identifies which clipboard to use using this code in /usr/share/nvim/runtime/autoload/provider/clipboard.vim

    elseif exists('$WAYLAND_DISPLAY') && executable('wl-copy') && executable('wl-paste')

**Comment by ferrine** [comment]
Did #43 help?

**Comment by the42** [comment]
Yeah, my bad. I read the README and wasn't aware that Wayland is supported. Just checked, it works. What a great plugin, that tremendously improves my markdown workflow!
