### ISSUE TITLE
I adapted the script to work with windows.

### ISSUE THREAD

**Issue by carlosen0153** [ferrine/md-img-paste.vim#5]
I am new to GitHub and could not find your mail to contact you.
I adapted the plugin to work with windows and powershell.
I would like to share it with you if you are interested.

**Comment by ferrine** [comment]
Hi, sure, my email is hidden to avoid annoying HRs) You can open a PR and I will walk you through, you are welcome

* fork my repo
* create a branch in your fork
* make changes, commit and push 
* go to my repo, you will see PR suggestion

**Comment by ferrine** [comment]
@carlosen-lopez do you need any help?

**Comment by ferrine** [comment]
I decided to support Unix systems only, sorry for that.
