### ISSUE TITLE
No working when I browse to another file

### ISSUE THREAD

**Issue by cdupont** [ferrine/md-img-paste.vim#51]
Hello,
the plugin works great when I open a simple file with vim: `vim myfile.md`.
However, once in vim I commonly use the explorer to browse to other files, with `:Explorer` or `:o`.
On the new file opened, it doesn't work. 

![Peek 2021-02-16 18-08](https://user-images.githubusercontent.com/484033/108097132-09f45900-7082-11eb-805a-500bb1cd637a.gif)

I use `<leader>p` key binding (explaining the strange paste behavior), it seems that in the other files the plugin doesn't work.

**Comment by ferrine** [comment]
Thanks for the report, I'll try to reproduce

**Comment by cdupont** [comment]
My bad, I actually had a bad key binding.
I had:
```
nmap <buffer><silent> <leader>p :call mdip#MarkdownClipboardImage()<CR>
```
But actually needed:
```
autocmd FileType markdown nmap <buffer><silent> <leader>p :call mdip#MarkdownClipboardImage()<CR>
```
I'm not so good in VI and was not sure what this `autocmd` was doing.
